/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormSignIn: typeof import('./components/FormSignIn.vue')['default']
    FormSignUp: typeof import('./components/FormSignUp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./components/Toast.vue')['default']
  }
}
